### ISSUE TITLE
Basic Functionality 

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/gis2coco#1]
**Context**

The current version of this utility is rough and ready, and was developed in a rather slap-dash fashion by me while working on building model pipelines. Current functionality includes converting a raster + geojson into a COCO data, or converting a set of raster tiles + a geojson into a COCO dataset.

**Next Steps**

- [ ] coco2gis conversion: to make GIS segmentation models useful, we need to be able to cast predictions back into GIS native forms (e.g. rasters and vector files). This conversion will need logic to decide how to merge predicted segmentations from adjacent tiles together. 
- [ ] performance improvements: the current conversion functionality does not sufficiently take advantage of efficient matrix/array processing techniques. Speed is acceptable, but performance increases could be easy as there are may inefficiencies in the current code base.
- [ ] tests: there need to be tests to make sure we know what is happening, what is working, and what isn't.
- [ ] documentation: readme needs to be expanded, and a google colab tutorial should be added.
- [ ] Support for more GIS formats: self explanatory
